export enum InstitutionType {
  GOVERNMENT = "GOVERNMENT",
  MUNICIPALITY = "MUNICIPALITY",
  TRANSIT_AUTHORITY = "TRANSIT_AUTHORITY",
  EMERGENCY = "EMERGENCY",
  INSURANCE = "INSURANCE",
  NGO = "NGO",
  OTHER = "OTHER",
}
