export enum ReportCategory {
  ACCIDENT = "ACCIDENT",
  TRAFFIC_LIGHT_DAMAGED = "TRAFFIC_LIGHT_DAMAGED",
  ROAD_DAMAGE = "ROAD_DAMAGE",
  ROAD_OBSTRUCTION = "ROAD_OBSTRUCTION",
  POOR_LIGHTING = "POOR_LIGHTING",
  MISSING_SIGNAGE = "MISSING_SIGNAGE",
  RECKLESS_DRIVING = "RECKLESS_DRIVING",
  DANGEROUS_CROSSING = "DANGEROUS_CROSSING",
  FLOOD_ZONE = "FLOOD_ZONE",
  OTHER = "OTHER",
}
